/* Bradford Smith (bsmith8)
 * CS 554 Lab 1 server.js
 * 09/05/2017
 */

var express = require('express');
var bodyParser = require('body-parser');
var data = require('./data.ja');

var app = express();

app.use(bodyParser.json()); //for parsing application/json
app.use(bodyParser.urlencoded({ extended: true })); //for parsing application/x-www-urlencoded

/* === middlewares ========================================================= */

/**
 * Log all request bodies, as well as the route they are requesting, and the
 * HTTP verb they are using.
 */
app.use(function(request, response, next) {
    console.log("HTTP " + request.method + " request for " + request.originalUrl + " with body: " + request.body);
    next();
});

/**
 * Keep track of how many times a particular URL has been requested, updating
 * and logging with each request.
 */
app.use(function(request, response, next) {
    //TODO
    next();
});

/* === routes begin here =================================================== */

/**
 * GET /api/tasks
 *
 * Shows a list of tasks. By default, it will show the first 20 tasks in the
 * collection. If a querystring variable `?skip=n` is provided, you will skip the
 * first `n` tasks. If a querystring variable `?take=y` is provided, it will
 * show `y` number of results. By default the route will show 20 tasks; at most,
 * it will show 100 tasks.
 */
app.get("/api/tasks", function (request, response) {
    //TODO
});

/**
 * GET /api/tasks/:id
 *
 * Shows the task with the supplied ID.
 */
app.get("/api/tasks/:id", function (request, response) {
    //TODO
});

/**
 * POST /api/tasks
 *
 * Creates a task with the supplied detail and returns the created object; fails
 * request if not all details are supplied.
 */
app.post("/api/tasks", function (request, response) {
    //TODO
});

/**
 * PUT /api/tasks/:id
 *
 * Updates the task with the supplied ID and returns the new task object;
 * **task**: PUT calls must provide deltas of the value to update! **Note** you
 * cannot manipulate comments in this route!
 */
app.put("/api/tasks/:id", function (request, response) {
    //TODO
});

/**
 * PATCH /api/tasks/:id
 *
 * Updates the task with the supplied ID and returns the new task object;
 * **task**: PATCH calls only provide deltas of the value to update! **Note**
 * you cannot manipulate comments in this route!
 */
app.patch("/api/tasks/:id", function (request, response) {
    //TODO
});

/**
 * POST /api/tasks/:id/comments
 *
 * Adds a new comment to the task; ids must be generated by the server, and not
 * supplied.
 */
app.post("/api/tasks/:id/comments", function (request, response) {
    //TODO
});

/**
 * DELETE /api/tasks/:taskId/:commentId
 *
 * Deletes the comment with an id of `commentId` on the task with an id of
 * `taskId`.
 */
app.delete("api/tasks/:taskId/:commentId", function (request, response) {
    //TODO
});
